title: "Jâ€™s Research"
description: "Papers on social chaos, hermeneutics, computational culture, and personal knowledge ecosystems."
theme: jekyll-theme-slate

markdown: kramdown
kramdown:
  math_engine: katex
